version: '3'
services:
  redis:
    image: redis
    ports:
    - "6379:6379"
  control-api:
    depends_on:
      - redis
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      REDIS_DATABASE:
      REDIS_PASSWORD:
      REDIS_PORT: 6379
      REDIS_HOST: redis